### ISSUE TITLE
Transform and displacement field output

### ISSUE THREAD

**Issue by simone-garzia** [moselhy/SlicerSequenceRegistration#5]
Hi! Thanks for the fantastic work! After performing the Sequence registration and obtaining the Transforms/ Displacement fields outputs, I was trying to perform the average operation of all the Tranforms obtained between the fixed and the moving volumes but I'm not currently able to do so in Slicer. So I was trying in Python saving Transforms as .mat files or with Displacement fields as .nrrd files. In any case, I'm having some issues because I don't know what type of parameters are in the .mat files or, for the displacement field case, I have only one matrix in the DisplacementFields.nrrd. Can you help me perform this average operation?

**Comment by lassoan** [comment]
The issue tracker here is for managing problems and feature requests. Please post this question to the Slicer forum - https://discourse.slicer.org -thank you!
